// Code generated by "stringer -type=StdMetrics"; DO NOT EDIT.

package metric

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _StdMetrics_name = "EuclideanSumSquaresCovarianceCorrelationCosineInvCosineInvCorrelationInnerProductAbsHammingCrossEntropyStdMetricsN"

var _StdMetrics_index = [...]uint8{0, 9, 19, 29, 40, 46, 55, 69, 81, 84, 91, 103, 114}

func (i StdMetrics) String() string {
	if i < 0 || i >= StdMetrics(len(_StdMetrics_index)-1) {
		return "StdMetrics(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StdMetrics_name[_StdMetrics_index[i]:_StdMetrics_index[i+1]]
}

func (i *StdMetrics) FromString(s string) error {
	for j := 0; j < len(_StdMetrics_index)-1; j++ {
		if s == _StdMetrics_name[_StdMetrics_index[j]:_StdMetrics_index[j+1]] {
			*i = StdMetrics(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: StdMetrics")
}
