// Code generated by "stringer -type=Aggs"; DO NOT EDIT.

package agg

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _Aggs_name = "AggCountAggSumAggProdAggMinAggMaxAggMeanAggVarAggStdAggSemAggVarPopAggStdPopAggSemPopAggMedianAggQ1AggQ3AggSumSqAggsN"

var _Aggs_index = [...]uint8{0, 8, 14, 21, 27, 33, 40, 46, 52, 58, 67, 76, 85, 94, 99, 104, 112, 117}

func (i Aggs) String() string {
	if i < 0 || i >= Aggs(len(_Aggs_index)-1) {
		return "Aggs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Aggs_name[_Aggs_index[i]:_Aggs_index[i+1]]
}

func (i *Aggs) FromString(s string) error {
	for j := 0; j < len(_Aggs_index)-1; j++ {
		if s == _Aggs_name[_Aggs_index[j]:_Aggs_index[j+1]] {
			*i = Aggs(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Aggs")
}
