// Code generated by numeric.gen.go.tmpl. DO NOT EDIT.

// Copyright (c) 2019, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package etable

// RowIdx encapsulates the simple logic for optionally using an index for row access.
// Use this for first index in accessing first row-major index in Table etensors.
// No length checking is done and access will panic if out of range.
func RowIdx(i int, idx []int) int {
	if idx != nil {
		return idx[i]
	}
	return i
}
