// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etable

const (
	Version     = "v1.1.18"
	GitCommit   = "df42d9d"          // the commit JUST BEFORE the release
	VersionDate = "2023-03-20 10:55" // UTC
)
