// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etable

const (
	Version     = "v1.1.6"
	GitCommit   = "9f1db70"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-11 19:43" // UTC
)
