// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etable

const (
	Version     = "v1.1.9"
	GitCommit   = "70d3c42"          // the commit JUST BEFORE the release
	VersionDate = "2022-10-02 11:37" // UTC
)
