ID = 'com.etable.v2'
Name = 'etable'
Type = 'Library'
Version = 'v2.0.0-dev0.0.16'

[Generate]
  [Generate.Enumgen]
    AcceptLower = true
    LineComment = true

[Release]
  Package = 'etable'
  VersionFile = 'etable/version.go'

[Web]
  LoadingLabel = ''
  RandomVersion = false
