// Code generated by "stringer -type=StdNorms"; DO NOT EDIT.

package norm

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

const _StdNorms_name = "L1L2SumSquaresNSumMeanVarStdMaxMaxAbsMinMinAbsStdNormsN"

var _StdNorms_index = [...]uint8{0, 2, 4, 14, 15, 18, 22, 25, 28, 31, 37, 40, 46, 55}

func (i StdNorms) String() string {
	if i < 0 || i >= StdNorms(len(_StdNorms_index)-1) {
		return "StdNorms(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StdNorms_name[_StdNorms_index[i]:_StdNorms_index[i+1]]
}

func (i *StdNorms) FromString(s string) error {
	for j := 0; j < len(_StdNorms_index)-1; j++ {
		if s == _StdNorms_name[_StdNorms_index[j]:_StdNorms_index[j+1]] {
			*i = StdNorms(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: StdNorms")
}
